-- Hippo grocery — catalog + store_content_blocks (deterministic UUIDs)
-- Apply after tenant schema + tables exist (pnpm schema:provision or Studio).
--
-- From this app directory with .env.local (same as storefront):
--   pnpm seed:apply
-- The API resolves your tenant from AURORA_API_KEY and substitutes __TENANT_UUID__ / __TENANT_SCHEMA__.
--
-- Re-run safe: deletes seed SKUs/slugs for this vertical before insert.
-- Category slugs are namespaced (hippo-grocery-*) so we do not delete tenant "vegetables" etc.
-- After apply: reindex Meilisearch for the tenant.

BEGIN;

DELETE FROM __TENANT_SCHEMA__.store_content_blocks WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug LIKE 'seed-cb-grocery-%';
DELETE FROM __TENANT_SCHEMA__.products WHERE tenant_id = '__TENANT_UUID__'::uuid AND sku LIKE 'SEED-HIPPO-GROCERY-%';
DELETE FROM __TENANT_SCHEMA__.categories WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug IN ('hippo-grocery-vegetables', 'hippo-grocery-beverages', 'hippo-grocery-snacks', 'hippo-grocery-bakery-items');
DELETE FROM __TENANT_SCHEMA__.zones WHERE tenant_id = '__TENANT_UUID__'::uuid AND slug = 'hippo-grocery-seed-zone';
DELETE FROM __TENANT_SCHEMA__.vendors WHERE tenant_id = '__TENANT_UUID__'::uuid AND id = 'a1000000-0000-4000-8000-000000000001'::uuid;

INSERT INTO __TENANT_SCHEMA__.vendors (id, tenant_id, name, email, status, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000001'::uuid, '__TENANT_UUID__'::uuid, 'Seed — Hippo Grocery supply', 'seed-grocery@example.com', 'active', now(), now());

INSERT INTO __TENANT_SCHEMA__.zones (id, tenant_id, slug, name, sort_order, vendor_id, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000002'::uuid, '__TENANT_UUID__'::uuid, 'hippo-grocery-seed-zone', 'Supermarket floor', 1, 'a1000000-0000-4000-8000-000000000001'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000011'::uuid, '__TENANT_UUID__'::uuid, 'Vegetables', 'hippo-grocery-vegetables', 'a1000000-0000-4000-8000-000000000002'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000012'::uuid, '__TENANT_UUID__'::uuid, 'Beverages', 'hippo-grocery-beverages', 'a1000000-0000-4000-8000-000000000002'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000013'::uuid, '__TENANT_UUID__'::uuid, 'Snacks & pantry', 'hippo-grocery-snacks', 'a1000000-0000-4000-8000-000000000002'::uuid, now(), now());
INSERT INTO __TENANT_SCHEMA__.categories (id, tenant_id, name, slug, zone_id, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000014'::uuid, '__TENANT_UUID__'::uuid, 'Bakery', 'hippo-grocery-bakery-items', 'a1000000-0000-4000-8000-000000000002'::uuid, now(), now());

INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000021'::uuid, '__TENANT_UUID__'::uuid, 'Organic Cherry Tomato 250g', 'Salads and quick sauces.', 2.49, 'SEED-HIPPO-GROCERY-01', 80, 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'a1000000-0000-4000-8000-000000000011'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, 'hero, new_arrival', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000022'::uuid, '__TENANT_UUID__'::uuid, 'Peeled Plum Tomatoes 4x400g', 'Passata-ready pantry line.', 3.99, 'SEED-HIPPO-GROCERY-02', 60, 'https://images.pexels.com/photos/5945562/pexels-photo-5945562.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'a1000000-0000-4000-8000-000000000011'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000023'::uuid, '__TENANT_UUID__'::uuid, 'Cloudy Apple Juice 6x330ml', 'Fridge-friendly multipack.', 4.50, 'SEED-HIPPO-GROCERY-03', 40, 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'a1000000-0000-4000-8000-000000000012'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000024'::uuid, '__TENANT_UUID__'::uuid, 'Organic Spaghetti 500g', 'Cupboard staple for quick dinners.', 2.20, 'SEED-HIPPO-GROCERY-04', 100, 'https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'a1000000-0000-4000-8000-000000000013'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, 'seasonal', now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000025'::uuid, '__TENANT_UUID__'::uuid, 'Pasta Sauce Basilico 400g', 'Pairs with dried pasta nights.', 2.80, 'SEED-HIPPO-GROCERY-05', 90, 'https://images.pexels.com/photos/5945562/pexels-photo-5945562.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'a1000000-0000-4000-8000-000000000013'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.products (id, tenant_id, name, description, price, sku, stock_quantity, image_url, category_id, vendor_id, tags, created_at, updated_at)
VALUES ('a1000000-0000-4000-8000-000000000026'::uuid, '__TENANT_UUID__'::uuid, 'Artisan Sourdough Loaf', 'Baked daily — freeze half for toast.', 3.40, 'SEED-HIPPO-GROCERY-06', 35, 'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'a1000000-0000-4000-8000-000000000014'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, NULL, now(), now());

INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000001-0000-4000-8000-000000000001'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-main-products', 0, 'home', 'home_main_feed', 'full', 'product_list', 'Pantry picks we stock for busy weeks', 'Organic pasta, passata-ready tomatoes, rice, and oil — one pass down the middle aisles.', NULL, NULL, NULL, NULL, 'a1000000-0000-4000-8000-000000000024,a1000000-0000-4000-8000-000000000025,a1000000-0000-4000-8000-000000000022,a1000000-0000-4000-8000-000000000021,a1000000-0000-4000-8000-000000000023,a1000000-0000-4000-8000-000000000026', NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000002-0000-4000-8000-000000000002'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-main-search', 1, 'home', 'home_main_feed', 'full', 'search_terms', 'Brands your household already trusts', 'One search pulls a mixed shelf — swap terms anytime in Studio.', NULL, NULL, NULL, NULL, NULL, 'Nescafe, Barilla, Weetabix, India Gate, Pompeian, Kelloggs', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000003-0000-4000-8000-000000000003'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-main-blurb', 2, 'home', 'home_main_feed', 'full', 'blurb', 'Shop the way you cook', NULL, 'Filter by aisle, dietary needs, or mission — then let Holmes suggest bundles and swaps from what is in stock. Your cart and For You page stay in sync so you never double-buy the heavy items.', NULL, '/catalogue', 'Browse full catalogue', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000004-0000-4000-8000-000000000004'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-main-half-a', 3, 'home', 'home_main_feed', 'half', 'blurb', 'Fresh produce first', NULL, 'Tomatoes, herbs, and loose veg pair with the organic and passata lines in our pantry rail — build a simple sauce night without a second trip.', NULL, '/catalogue?category=hippo-grocery-vegetables', 'Vegetables', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000005-0000-4000-8000-000000000005'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-main-half-b', 4, 'home', 'home_main_feed', 'half', 'blurb', 'Breakfast in two taps', NULL, 'Cereals plus Nescafe and creamer-style lines show up when you search from For You — add milk or juice from Dairy and Beverages in one pass.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000006-0000-4000-8000-000000000006'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-main-image', 5, 'home', 'home_main_feed', 'full', 'image_blurb', 'This week''s price drops', NULL, 'Replace this placeholder image with your weekly deals banner. Tie the CTA to live offers so seasonal produce and bundle SKUs get the spotlight.', 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/offers', 'See current offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000007-0000-4000-8000-000000000007'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-below-well', 1, 'home', 'home_below_context_well', 'full', 'blurb', 'Smart cart remembers weight', NULL, 'Slot reserved above the feed: use it for delivery cut-off times, minimum-order nudges, or weather-based substitutions. Not rendered on the home template yet — available via API with page=home, region=home_below_context_well.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000008-0000-4000-8000-000000000008'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-between-missions', 1, 'home', 'home_between_missions_and_feed', 'full', 'blurb', 'Missions & rewards', NULL, 'When this region is wired, place a short line explaining recipe missions, streaks, or loyalty — keep it under two sentences so the feed loads fast.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000009-0000-4000-8000-000000000009'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-home-below-feed', 1, 'home', 'home_below_feed', 'full', 'blurb', 'Still hungry for ideas?', NULL, 'Footer rail for newsletter signup, store hours, or shop last order again. Hook: recipes_index_below_header and /recipes stay linked from the main nav.', NULL, '/recipes', 'Recipe ideas', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200000a-0000-4000-8000-00000000000a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-for-you-blocks', 1, 'for_you', 'for_you_below_cart_blocks', 'full', 'search_terms', 'Fill the gaps before checkout', 'Snacks, drinks, and breakfast add-ons that match what is already in your basket.', NULL, NULL, NULL, NULL, NULL, 'Mini Cheddars, Haldiram, Sprite, Kelloggs, Nescafe, Mandarins', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200000b-0000-4000-8000-00000000000b'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-for-you-header', 1, 'for_you', 'for_you_below_header', 'full', 'blurb', 'Personalised from your cart', NULL, 'Holmes keeps bundle and cross-sell rails. This CMS strip is for editorial nudges (e.g. Add fruit for school lunches). Wire the region when you want copy directly under the For You heading.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200000c-0000-4000-8000-00000000000c'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-cat-above', 1, 'catalogue', 'catalogue_above_grid', 'full', 'blurb', 'Everything in one grid', NULL, 'Use filters for category, store, and dietary tags. Search understands recipe-style queries — try an ingredient or brand. Product images respect your tenant image base URL.', NULL, '/catalogue', 'Reset filters', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200000d-0000-4000-8000-00000000000d'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-cat-below', 1, 'catalogue', 'catalogue_below_filters', 'full', 'search_terms', 'Popular searches right now', 'OR-style query across organic lines, staples, and produce.', NULL, NULL, NULL, NULL, NULL, 'organic, basmati, tomato, olive oil, cereal, Nescafe', NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200000e-0000-4000-8000-00000000000e'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-cat-beverages', 2, 'catalogue', 'catalogue_below_filters', 'full', 'blurb', 'Drinks & refills', NULL, 'You are in Beverages — look for multipack savings on juice and soft drinks, then grab coffee or tea for the week. Bundle with snacks from the Snacks aisle for movie night.', NULL, '/catalogue?category=hippo-grocery-snacks', 'Pair with snacks', NULL, NULL, NULL, NULL, NULL, 'hippo-grocery-beverages', now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200000f-0000-4000-8000-00000000000f'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-pdp-tabs', 1, 'product_detail', 'pdp_below_tabs', 'full', 'blurb', 'How we show nutrition', NULL, 'Ingredients and allergens come from the catalogue record. If something looks off, flag it in Studio — PDP blocks are perfect for prepared in a facility that handles nuts style disclaimers.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000010-0000-4000-8000-000000000010'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-pdp-context', 1, 'product_detail', 'pdp_below_context', 'full', 'blurb', 'Storage & satisfaction', NULL, 'Short tip: chilled lines should go straight in the fridge. Dry goods keep best sealed. Link to your returns policy if you offer freshness guarantees.', NULL, '/about', 'Our standards', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000011-0000-4000-8000-000000000011'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-recipe-title', 1, 'recipe', 'recipe_below_title', 'full', 'blurb', 'Cook along', NULL, 'Timers and servings stay in the recipe view. Use this strip for chef tips or swap dairy for oat notes without cluttering the steps.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000012-0000-4000-8000-000000000012'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-recipe-ingredients', 1, 'recipe', 'recipe_below_ingredients', 'full', 'blurb', 'Missing one ingredient?', NULL, 'Jump to search with the ingredient name, or open For You — Holmes often surfaces the bundle that completes the dish.', NULL, '/for-you', 'Open For You', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000013-0000-4000-8000-000000000013'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-recipe-index', 1, 'recipe_index', 'recipes_index_below_header', 'full', 'blurb', 'Meals planned around your basket', NULL, 'Each recipe pulls from real catalogue matches. Start a mission from home to auto-fill ingredients, then tweak quantities before checkout.', NULL, '/', 'Back to home', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000014-0000-4000-8000-000000000014'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-checkout-summary', 1, 'checkout', 'checkout_above_summary', 'full', 'blurb', 'You are almost done', NULL, 'Payments are encrypted. Delivery slots can move during peak hours — we will confirm before charging. Substitutions follow your basket preferences.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000015-0000-4000-8000-000000000015'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-checkout-sidebar', 1, 'checkout', 'checkout_sidebar', 'full', 'blurb', 'Need help?', NULL, 'Chat opens from the Holmes bubble. For order changes, reference your confirmation email. Sidebar CMS is ideal for support hours and FAQ links.', NULL, '/about', 'Contact & FAQs', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000016-0000-4000-8000-000000000016'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-cart-above', 1, 'cart', 'cart_above_lines', 'full', 'blurb', 'Review before you pay', NULL, 'Quantities sync with For You and missions. Remove chilled items you no longer need — pickers pack in route order to keep temperature stable.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000017-0000-4000-8000-000000000017'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-cart-below-bundle', 1, 'cart', 'cart_below_bundle', 'full', 'blurb', 'Complete the meal', NULL, 'Holmes may suggest a bundle under your lines. This block is for static cross-sell copy (e.g. Add bread for soup night).', NULL, '/catalogue?category=hippo-grocery-bakery-items', 'Bakery aisle', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000018-0000-4000-8000-000000000018'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-offers', 1, 'offers', 'offers_below_header', 'full', 'blurb', 'Live savings', NULL, 'Offers pull from your data model. This strip can highlight stackable deals (mix any 3 breakfast lines). Keep messaging short — the grid below is the hero.', NULL, '/catalogue', 'Shop all', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b2000019-0000-4000-8000-000000000019'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-promotions', 1, 'promotions', 'promotions_below_header', 'full', 'blurb', 'Campaigns & seasonal', NULL, 'Use promotions for limited-time events (Ramadan bundles, back-to-school, BBQ week). Match imagery in Studio to the same dates as your email campaigns.', NULL, '/offers', 'See offers', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());
INSERT INTO __TENANT_SCHEMA__.store_content_blocks (id, tenant_id, slug, sort_order, page, region, width, block_kind, title, subtitle, body, image_url, link_url, link_label, product_ids, search_terms, time_of_day, day_of_week, holiday_key, category_slug, created_at, updated_at)
VALUES ('b200001a-0000-4000-8000-00000000001a'::uuid, '__TENANT_UUID__'::uuid, 'seed-cb-grocery-about', 1, 'about', 'about_main', 'full', 'image_blurb', 'Hippo Grocery', NULL, 'We combine Aurora catalogue data, Holmes personalisation, and these CMS blocks so your team can merchandise without redeploying the app. Replace the image with your store front, team, or local growers.', 'https://images.pexels.com/photos/264507/pexels-photo-264507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '/catalogue', 'Start shopping', NULL, NULL, NULL, NULL, NULL, NULL, now(), now());

COMMIT;
